src/Entity/MenuItem.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\MenuItemsRepository")
 * @ORM\HasLifecycleCallbacks
 */
class MenuItem
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    public function getId()
    {
        return $this->id;
    }

    /**
     * @ORM\Column(type="text")
     */
    private $name;

    public function getName()
    {
        return $this->name;
    }

    public function setName($name)
    {
        $this->name = $name;
    }

    /**
     * @ORM\Column(type="text")
     */
    private $link;

    public function getLink()
    {
        return $this->link;
    }

    public function setLink($link)
    {
        $this->link = $link;
    }
    /**
     * @ORM\Column(type="integer", nullable=TRUE)
     */
    private $ordering;

    public function getOrdering()
    {
        return $this->ordering;
    }

    public function setOrdering($ordering)
    {
        $this->ordering = $ordering;
    }

    /**
     * @ORM\Column(type="boolean")
     */
    private $deleted;

    public function getDeleted()
    {
        return $this->deleted;
    }

    public function setDeleted($deleted)
    {
        $this->deleted = $deleted;
    }

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\MenuCategory", inversedBy="menuItems")
     * @ORM\JoinColumn(nullable=false)
     */
    private $Parent;

    public function getParent(): ?MenuCategory
    {
        return $this->Parent;
    }

    public function setParent(?MenuCategory $Parent): self
    {
        $this->Parent = $Parent;

        return $this;
    }

}

templates/inc/calendar.html.twig
{% block body %}
    <style>
        .table-style .today {background: #2A3F54; color: #ffffff;}
        .table-style th:nth-of-type(7),td:nth-of-type(7) {color: blue;}
        .table-style th:nth-of-type(1),td:nth-of-type(1) {color: red;}
        .table-style tr:first-child th{background-color:#F6F6F6; text-align:center; font-size: 15px;}
    </style>

<div style="border:0px solid">
    <div style="padding:0px;">
        <br>
        <table class="table table-bordered table-style table-responsive">
            <tr>
                <th colspan="2"><a href="?ym=<?php echo $prev; ?>"><span class="glyphicon glyphicon-chevron-left"></span></a></th>
                <th colspan="3"> Jan - 2017<!--?php echo $html_title; ?--></th>
                <th colspan="2"><a href="?ym=<?php echo $next; ?>"><span class="glyphicon glyphicon-chevron-right"></span></a></th>
            </tr>
            <tr>
                <th>S</th>
                <th>M</th>
                <th>T</th>
                <th>W</th>
                <th>T</th>
                <th>F</th>
                <th>S</th>
            </tr>
            <tr>
                <td>1</td>
                <td>2</td>
                <td>3</td>
                <td>4</td>
                <td>5</td>
                <td>6</td>
                <td>7</td>
            </tr>
            <tr>
                <td>8</td>
                <td>9</td>
                <td>10</td>
                <td>11</td>
                <td class="today">12</td>
                <td>13</td>
                <td>14</td>
            </tr>
            <tr>
                <td>15</td>
                <td>16</td>
                <td>17</td>
                <td>18</td>
                <td>19</td>
                <td>20</td>
                <td>21</td>
            </tr>
            <tr>
                <td>22</td>
                <td>23</td>
                <td>24</td>
                <td>25</td>
                <td>26</td>
                <td>27</td>
                <td>28</td>
            </tr>
            <tr>
                <td>29</td>
                <td>30</td>
                <td>31</td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>

            <!--?php
              foreach ($weeks as $week) {
                echo $week;
              };
            ?-->
        </table>

    </div>
</div>













<!-- <?php
// Set your timezone!!
date_default_timezone_set('Asia/Dhaka');

// Get prev & next month
if (isset($_GET['ym'])) {
 $ym = $_GET['ym'];
} else {
 // This month
 $ym = date('Y-m');
}

// Check format
$timestamp = strtotime($ym,"-01");
if ($timestamp === false) {
 $timestamp = time();
}

// Today
$today = date('Y-m-j', time());

// For H3 title
$html_title = date('M - Y', $timestamp);

// Create prev & next month link     mktime(hour,minute,second,month,day,year)
$prev = date('Y-m', mktime(0, 0, 0, date('m', $timestamp)-1, 1, date('Y', $timestamp)));
$next = date('Y-m', mktime(0, 0, 0, date('m', $timestamp)+1, 1, date('Y', $timestamp)));

// Number of days in the month
$day_count = date('t', $timestamp);

// 0:Sun 1:Mon 2:Tue ...
$str = date('w', mktime(0, 0, 0, date('m', $timestamp), 1, date('Y', $timestamp)));


// Create Calendar!!
$weeks = array();
$week = '';

// Add empty cell
$week .= str_repeat('<td></td>', $str);

for ( $day = 1; $day <= $day_count; $day++, $str++) {

 $date = $ym.'-'.$day;

 if ($today == $date) {
     $week .= '<td class="today">'.$day;
 } else {
     $week .= '<td>'.$day;
 }
 $week .= '</td>';

 // End of the week OR End of the month
 if ($str % 7 == 6 || $day == $day_count) {

     if($day == $day_count) {
         // Add empty cell
         $week .= str_repeat('<td></td>', 6 - ($str % 7));
     }

     $weeks[] = '<tr>'.$week.'</tr>';

     // Prepare for new week
     $week = '';

 }

}

?>-->
{% endblock %}

templates/inc/footer.html.twig
<!-- Footer -->
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">

<footer class="page-footer font-small bg-primary pt-4">

    <!-- Footer Links -->
    <div class="container text-center text-md-left text-secondary">

        <!-- Grid row -->
        <div class="row">

            <!-- Grid column -->
            <div class="col-md-6 col-lg-4 mr-auto my-md-4 my-0 mt-4 mb-1">

                <div class="row pl-2">
                    <a href="/"><img src="/img/logo/RKN/RKN.png" style="height: 80px"></a>
                    <br><br>
                </div>
                <br>
                <h5 class="font-weight-bold text-uppercase mb-1">Zobacz też</h5>
                <br>
                <div class="row">
                    <div class="col">
                        <a href="https://www.pw.edu.pl"><img src="/img/logo/PW/znak-pw.png" style="height: 50px"></a>
                    </div>
                    <div class="col">
                        <a href="https://sspw.pl"><img src="/img/logo/SSPW/SSPW.png" style="height: 50px"></a>
                    </div>
                </div>
            </div>


            <!-- Grid column -->

            <hr class="clearfix w-100 d-md-none">

            <!-- Grid column -->
            <div class="col-md-4 col-lg-4 mx-auto my-md-4 my-0 mt-4 mb-1">

                <!-- Contact details -->
                <h5 class="font-weight-bold text-uppercase mb-4">Kontakt</h5>

                <ul class="list-unstyled">
                    <li>
                        <p>
                            <i class="fa fa-home mr-3"></i> Warszawa, ul. Rektorska 4/3.15
                        </p>
                    </li>
                    <li>
                        <p>
                            <i class="fa fa-envelope mr-3"></i> zarzad@rkn.pw.edu.pl
                        </p>
                    </li>
                    <li>
                        <p>
                            <i class="fa fa-phone mr-3"></i> + 0 22 234 50 10
                        </p>
                    </li>
                    <li>
                        <p>
                            <i class="fa fa-mobile-alt mr-3"></i> + 48 781 150 922
                        </p>
                    </li>
                </ul>

            </div>
            <!-- Grid column -->

            <hr class="clearfix w-100 d-md-none">

            <!-- Grid column -->
            <div class="col-md-2 col-lg-2 text-center mx-auto my-4">

                <!-- Social buttons -->
                <h5 class="font-weight-bold text-uppercase mb-4">Obserwuj Nas</h5>

                <!-- Lista mailingowa -->
                    <a class="text-secondary" href="http://listy.samorzad.pw.edu.pl/mailman/listinfo/kola" style="text-decoration: none"><i class="fas fa-envelope-square fa-2x"></i><br></a>
                <!-- Facebook -->
                <a class="text-secondary" href="https://web.facebook.com/rknpw" style="text-decoration: none"><i class="fab fa-facebook-square fa-2x"></i><br></a>

                <!-- Twitter -->
                <a class="text-secondary" href="https://twitter.com/rkn_pw" style="text-decoration: none"> <i class="fab fa-twitter-square fa-2x"></i><br></a>
                <!-- Youtube -->
                <a class="text-secondary" href="https://www.youtube.com/channel/UC18t3oal-5cmDhtX3u3i37Q" style="text-decoration: none"><i class="fab fa-youtube-square fa-2x"></i><br></a>
                <!-- Instagram -->
                <a class="text-secondary" href="https://instagram.com/rkn_pw" style="text-decoration: none"><i class="fab fa-instagram fa-2x"></i></a>

            </div>
            <!-- Grid column -->

        </div>
        <!-- Grid row -->

    </div>
    <!-- Footer Links -->

    <!-- Copyright -->
    <div class="footer-copyright bg-secondary text-light mt-0 mb-0" style="height: 30px; text-align: center">© 2018 Copyright: A.T.M.
    </div>
    <!-- Copyright -->

</footer>
<!-- Footer -->

templates/inc/navbar.html.twig
<nav class="navbar navbar-expand-lg navbar-light text-secondary bg-primary">
    <a class="navbar-brand" href="/"><img src="/img/logo/RKN/RKN.png" style="height: 80px"></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse text-secondary" id="navbarColor01">
        <ul class="navbar-nav mr-auto text-secondary">
            {% for cat in categories %}
                {% if cat.hasChildren %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="'navbarDropdown" role="button" data-toggle="dropdown">{{ cat.name }}<span class="sr-only">(current)</span></a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            {% for item in items %}
                                {% if item.parent == cat %}
                                    {% if item.name == '<divider>' %}
                                        <div class="dropdown-divider"></div>
                                    {% else %}
                                        <a class="dropdown-item" href="{{ item.link }}">{{ item.name }}</a>
                                    {% endif %}
                                {% endif %}
                            {% endfor %}
                        </div>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ cat.link }}">{{ cat.name }}</a>
                    </li>
                {% endif %}
            {% endfor %}

        </ul>
        <div class="nav navbar-nav pull-right text-secondary" id="navbarColor01">
            <ul class="pull-right navbar-nav mr-auto text-secondary">
                {% if is_granted('IS_AUTHENTICATED_FULLY') %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown">
                            Twoje Koła <span class="sr-only">(current)</span>
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            {% for kn in app.user.researchGroups %}
                            <a class="dropdown-item" href="/kn/{{ kn.id }}/members">{{ kn.nameShort }}</a>
                            {% endfor %}
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle text-light" data-toggle="dropdown"><i class="fas fa-user-circle"></i>
                            Cześć {{ app.user.name }} {{ app.user.surname }}
                        </a>
                        <ul class="dropdown-menu dropdown-menu-right">
                            <li ><a class="dropdown-item" href="/logout"><i class="icon-off"></i>Logout</a></li>
                            {% if is_granted('ROLE_site_admin') %}
                                <li><a class="dropdown-item" href="/menu"><i class="icon-off"></i>Edytuj menu</a></li>
                            {% endif %}
                        </ul>
                    </li>
                {% else %}
                    <li class="nav-item pull-right">
                        <a class="nav-link" href="/login"><i class="fas fa-sign-in-alt"></i>  Login</a>
                    </li>
                {% endif %}
                {#<li class="dropdown"><a href="#" class="dropdown-toggle text-light" data-toggle="dropdown"><i class="fas fa-user-circle"></i> User <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li><a href="/user/preferences"><i class="icon-cog"></i> Preferences</a></li>
                        <li><a href="/help/support"><i class="icon-envelope"></i> Contact Support</a></li>
                        <li class="divider"></li>
                        <li><a href="/auth/logout"><i class="icon-off"></i> Logout</a></li>
                    </ul>
                </li>#}
            </ul>
        </div>
    </div>
</nav><br>